Implement element_at
rxRust/rxRust pull request #123
Opened 2020-12-09 02:40 UTC by godhand4826

Where to write the test? Please help.

2020-12-09 11:58 UTC, M-Adoo commented
Thanks!  Just add a test mod at the end of the file.

2020-12-10 03:10 UTC, godhand4826 commented
Thanks for you help, Great!

2020-12-13 12:23 UTC, M-Adoo requested changes
Looks great,  thank you very much and some suggestions for you.

2020-12-13 12:23 UTC, M-Adoo commented on src/ops/ignore_elements.rs
> +impl<Item, Err, S, Unsub> LocalObservable<'static> for IgnoreElementsOp<S>
Should not only implement `LocalObservable<'static>`, use a general lifetime please.

2020-12-13 12:23 UTC, M-Adoo commented on src/ops/ignore_elements.rs
> +struct SharedIgnoreElementsObserver<O>(Arc<Mutex<IgnoreElementsObserver<O>>>);
You needn't wrap new type with `Arc` and `Rc`, just directly  implement `Observer` for `IgnoreElementsObserver` is enough.

2020-12-14 02:51 UTC, godhand4826 commented on src/ops/ignore_elements.rs
> +struct SharedIgnoreElementsObserver<O>(Arc<Mutex<IgnoreElementsObserver<O>>>);
Thanks for your reply!
I'm new about rust. 
For my understanding, to shared a object should wrap with Rc<_>.
To shared a object between threads should wrap with Arc<Mutex<_>>
Why here don't need to? Am I misunderstanding or missing something?

2020-12-14 04:10 UTC, M-Adoo commented on src/ops/ignore_elements.rs
> +struct SharedIgnoreElementsObserver<O>(Arc<Mutex<IgnoreElementsObserver<O>>>);
You are right. But  you can directly use `Arc` and `Rc`,   new  type `SharedIgnoreElementsObserver`  with `Arc` is needn't, same to the local version.

2020-12-14 10:01 UTC, godhand4826 commented
Re-implement ignore_elements with general lifetime. :+1:

2020-12-15 15:04 UTC, M-Adoo approved these changes
Looks good, thanks.

2020-12-16 12:12 UTC, godhand4826 commented
Refactor skip_last operator.
Sorry, I forgot to create branch before refactor.

2020-12-17 15:14 UTC, M-Adoo approved these changes
Thanks！

2020-12-17 16:15 UTC, merged