Implement element_at, ignore_elements, refactor distinct
rxRust/rxRust pull request #124
Opened 2020-12-18 06:59 UTC by godhand4826

Sorry, I force push when "Refactor skip_last operator".  (See #123)
I create  "Implement element_at, ignore_elements, refactor distinct" PR again.

2020-12-21 12:48 UTC, M-Adoo commented
Can you update the changle log?

2020-12-22 16:34 UTC, M-Adoo requested changes

2020-12-22 16:34 UTC, M-Adoo commented on CHANGELOG.md
> +- **operator**: add `element_at` operator.
Should add the features and refactor below the `Unreleased`,  not add in a released version `0.10.0.

2020-12-23 02:11 UTC, godhand4826 commented on CHANGELOG.md
> +- **operator**: add `element_at` operator.
Okay

2020-12-23 02:18 UTC, godhand4826 commented on CHANGELOG.md
> +- **operator**: add `element_at` operator.
Done

2020-12-23 12:22 UTC, M-Adoo approved these changes
Thanks!

2020-12-23 12:23 UTC, merged