feat: 🎸 Implement combine_latest operator
rxRust/rxRust pull request #162
Opened 2021-11-12 04:44 UTC by wufniks

Implemented combine_latest operator. It emits item which is combining latest items from two observables.

2021-11-17 15:03 UTC, M-Adoo commented on src/ops/combine_latest.rs
> +  pub(crate) _marker: TypeHint<*const OutputItem>,
Seems unnecessary generic type `OutputItem` as the return type of `BinaryOp`, it's can be constrained.

2021-11-17 15:08 UTC, M-Adoo requested changes
In the `1.0-alpha` branch,  I provide a macro to implement both local & shared observable once time. You can try it if possible, it doesn't matter if you use the current implementation

2021-11-18 17:37 UTC, wufniks commented on src/ops/combine_latest.rs
> +  pub(crate) _marker: TypeHint<*const OutputItem>,
Done in 20b200d. But I am not quite sure if I understand you correctly, since I don't know much about generic types. So please let me know this is not what you meant.

2021-11-19 00:56 UTC, wufniks commented
Seems like I can't use `FnMut` bound in the `where` clause of `impl_local_share_both` macro. I got error like following.
```rust
error: macro expansion ignores token `,` and any following
   --> src/ops/combine_latest.rs:41:28
    |
41  |       BinaryOp: FnMut(A::Item, B::Item) -> OutputItem
    |                              ^
    |
   ::: src/impl_helper.rs:192:4
    |
192 | /    impl_local_share_both!{
193 | |      @replace$(+$i)*, $ctx,
194 | |      [$($before)* $caller ] $($t)*
195 | |    }
    | |____- caused by the macro expansion here
    |
    = note: the usage of `impl_local_share_both!` is likely invalid in type context
```

I've searched operators with `FnMut` bounds for the reference, but none of them is using `impl_local_share_both` macro. Are there any chance that the feature(function bounds for the macro) is not implemented yet?

2021-11-19 14:39 UTC, M-Adoo commented on src/ops/combine_latest.rs
> +  pub(crate) _marker: TypeHint<*const OutputItem>,
Yes, that what i meant.

2021-11-19 14:43 UTC, M-Adoo commented
> Seems like I can't use `FnMut` bound in the `where` clause of `impl_local_share_both` macro. I got error like following.
> 
> ```rust
> error: macro expansion ignores token `,` and any following
>    --> src/ops/combine_latest.rs:41:28
>     |
> 41  |       BinaryOp: FnMut(A::Item, B::Item) -> OutputItem
>     |                              ^
>     |
>    ::: src/impl_helper.rs:192:4
>     |
> 192 | /    impl_local_share_both!{
> 193 | |      @replace$(+$i)*, $ctx,
> 194 | |      [$($before)* $caller ] $($t)*
> 195 | |    }
>     | |____- caused by the macro expansion here
>     |
>     = note: the usage of `impl_local_share_both!` is likely invalid in type context
> ```
> 
> I've searched operators with `FnMut` bounds for the reference, but none of them is using `impl_local_share_both` macro. Are there any chance that the feature(function bounds for the macro) is not implemented yet?

It's should support. Would you provide the full macro code or a branch ? I would like to fix it if there is a bug in the macro implementation.

2021-11-19 17:27 UTC, M-Adoo commented
`FnMut` work in  https://github.com/rxRust/rxRust/blob/1.0-alpha/src/ops/skip_until.rs

2021-11-20 00:50 UTC, wufniks commented
> Would you provide the full macro code or a branch ?

My WIP branch is https://github.com/wufniks/rxRust/tree/feature/rebased-combine-latest.
And full macro looks like following.

```rust
impl_local_share_both! {
  impl<'a, A, B, BinaryOp, OutputItem> CombineLatestOp<A, B, BinaryOp>;
  type Unsub = @ctx::RcMultiSubscription;
  macro method($self: ident, $observer: ident, $ctx: ident) {
    let sub= $ctx::RcMultiSubscription::default();
    let o_combine = $ctx::Rc::own(CombineLatestObserver::new(
      $observer,
      sub.clone(),
      $self.binary_op,
    ));
    let o_combine = Rc::new(RefCell::new(o_combine));
    sub.add($self.a.actual_subscribe(AObserver(o_combine.clone(), TypeHint::new())));
    sub.add($self.b.actual_subscribe(BObserver(o_combine, TypeHint::new())));
    sub
  }
  where
    @ctx::local_only(
      BinaryOp: FnMut(A::Item, B::Item) -> OutputItem + 'a,
      A::Item: Clone + 'a,
      B::Item: Clone + 'a
    )
    @ctx::shared_only(
      BinaryOp: FnMut(A::Item, B::Item) -> OutputItem + Send + Sync + 'static,
      A::Item: Clone + Send + Sync + 'static,
      B::Item: Clone + Send + Sync + 'static
    )
}
```

2021-11-20 14:08 UTC, M-Adoo commented
> > Would you provide the full macro code or a branch ?
> 
> My WIP branch is [wufniks/feature/rebased-combine-latest](https://github.com/wufniks/rxRust/tree/feature/rebased-combine-latest). And full macro looks like following.
> 
> ```rust
> impl_local_share_both! {
>   impl<'a, A, B, BinaryOp, OutputItem> CombineLatestOp<A, B, BinaryOp>;
>   type Unsub = @ctx::RcMultiSubscription;
>   macro method($self: ident, $observer: ident, $ctx: ident) {
>     let sub= $ctx::RcMultiSubscription::default();
>     let o_combine = $ctx::Rc::own(CombineLatestObserver::new(
>       $observer,
>       sub.clone(),
>       $self.binary_op,
>     ));
>     let o_combine = Rc::new(RefCell::new(o_combine));
>     sub.add($self.a.actual_subscribe(AObserver(o_combine.clone(), TypeHint::new())));
>     sub.add($self.b.actual_subscribe(BObserver(o_combine, TypeHint::new())));
>     sub
>   }
>   where
>     @ctx::local_only(
>       BinaryOp: FnMut(A::Item, B::Item) -> OutputItem + 'a,
>       A::Item: Clone + 'a,
>       B::Item: Clone + 'a
>     )
>     @ctx::shared_only(
>       BinaryOp: FnMut(A::Item, B::Item) -> OutputItem + Send + Sync + 'static,
>       A::Item: Clone + Send + Sync + 'static,
>       B::Item: Clone + Send + Sync + 'static
>     )
> }
> ```

Sorry, I found the macro is not work with `FnMut` which  has more than one arguments.  So let merge this pr without using the macro.

2021-11-20 14:09 UTC, M-Adoo submitted a review, later dismissed

2021-11-20 15:10 UTC, wufniks commented
Sorry for inconvenience, but I just added another commit for formatting.

2021-11-20 15:38 UTC, M-Adoo approved these changes
Thanks!

2021-11-20 15:41 UTC, merged

2021-11-20 16:15 UTC, M-Adoo commented
@wufniks  I fixed the macro bug, and use it in your operator, maybe you would like to review it,  https://github.com/rxRust/rxRust/blob/04a739a45539fee932ba3d7fff29e63e992d474b/src/ops/combine_latest.rs.