Add operator 'WithLatestFrom'
rxRust/rxRust pull request #165
Opened 2021-11-22 06:09 UTC by utilForever

This revisions includes:
- Add operator 'WithLatestFrom' (See https://rxmarbles.com/#withLatestFrom)
  - Create struct 'WithLatestFromOp'
  - Add function 'with_latest_from()'

p.s. I tried to inspire my implementation on operator 'Zip'.

2021-11-22 06:34 UTC, utilForever commented
@M-Adoo This failure of GitHub Actions is not my fault.
```sh
failures:
    ops::observe_on::test::switch_thread
```
You should check it. 😢

2021-11-23 17:09 UTC, M-Adoo requested changes
Thanks! It's looks good to me.  Could you rebase the branch and squash the commits ?

2021-11-23 17:32 UTC, utilForever commented
@M-Adoo I rebased the branch and squashed the commits! 😄

2021-11-23 17:48 UTC, M-Adoo approved these changes

2021-11-23 17:49 UTC, merged