feat: allow for side effect in flat_map and flat_map_threads
rxRust/rxRust pull request #233
Opened 2023-06-13 15:51 UTC by Atry

2023-06-14 04:52 UTC, M-Adoo requested changes
Looks good, please rebase the master and update the `CHANGELOG.md`

2023-06-14 16:09 UTC, Atry commented
Revised as requested

2023-06-15 02:38 UTC, M-Adoo approved these changes

2023-06-16 03:11 UTC, wjian23 approved these changes

2023-06-16 03:13 UTC, merged